### ISSUE TITLE
Adding all the required functionalities

### ISSUE THREAD

**Issue by Bhum-ika** [anuj123upadhyay/MegaBlog#1]
Hi, 
It can have multiple users with their own blogs and with the feature of adding , deleting, editing.
I can use firebase and react for the same, and will make it responsive too.
Kindly assign this issue to me so I can start working

**Comment by Bhum-ika** [comment]
Please add the gssocext and hactoberfest badges

**Comment by Bhum-ika** [comment]
Can i start working on this??

**Comment by anuj123upadhyay** [comment]
yes you can solve this issue

**Comment by anuj123upadhyay** [comment]
best of luck

**Comment by Bhum-ika** [comment]
Please add the gssoc-ext and hactoberfest badges and assign the level too.
Thank you

**Comment by anuj123upadhyay** [comment]
I think try to use Appwrite instead of firebase

**Comment by Bhum-ika** [comment]
Okay , let me see, I will update you on the progress.

**Comment by Bhum-ika** [comment]
Hi, 

I was working on it, but Appwrite is not providing India region due to which we will have to wait till they notify us for the availability.
I still tried with different region , but it's not working
