### ISSUE TITLE
Making the copyright year dynamic

### ISSUE THREAD

**Issue by ZoyaYusuf** [anuj123upadhyay/MegaBlog#115]
<img width="443" alt="Screenshot 2024-10-10 at 9 14 01 PM" src="https://github.com/user-attachments/assets/18a47928-0d30-4b2a-879d-ef36ef530caf">

As you can see in the screenshot of the code snippet that the year 2023 is static, and does not change automatically when the year changes.
i want to make it dynamic so that it can change according to the present year.
Please assign me this issue with **gssoc-extd** , **level** and **hacktober** labels 
Thankyou :)

**Comment by anuj123upadhyay** [comment]
okk make it dynamic as the year changes according to the current year

**Comment by ZoyaYusuf** [comment]
@anuj123upadhyay could you please add **hacktoberfest-accespted** label as well. 
Thankyou :)
