### ISSUE TITLE
Icons Get started and Learn more not linked to any pages

### ISSUE THREAD

**Issue by vasudhawaman** [anuj123upadhyay/MegaBlog#116]
[RecordedVideo (7).webm](https://github.com/user-attachments/assets/be5a6f02-632a-4641-8cf6-f22ca5557094)

**Comment by anuj123upadhyay** [comment]
i would like if you link "get started" button to "add post page"   and   "learn more " button to "all-post page " so that people can learn from them

**Comment by vasudhawaman** [comment]
@anuj123upadhyay  can you also add hacktoberfest labels ?
