### ISSUE TITLE
Adding Features Page 

### ISSUE THREAD

**Issue by govindumeesala** [anuj123upadhyay/MegaBlog#119]
Adding a pages that shows features that we offer gives more readability and enhances user experience.

And linking it to the footer.

![image](https://github.com/user-attachments/assets/eec9d5fe-cff5-437f-918c-86c2156c2118)

@anuj123upadhyay please assign this to me.

**Comment by anuj123upadhyay** [comment]
Okk , i assign this to you, but make it which looks good with the existing theme of the whole application
