### ISSUE TITLE
[UI Enhancement]: Add motion animations to Liscensing Page

### ISSUE THREAD

**Issue by inkerton** [anuj123upadhyay/MegaBlog#123]
Hi @anuj123upadhyay 

Assign this issue to me please under gssoc-ext. I will add motion animations similar to the Privacy Policy Page to the Licensing Page.
It is currently just a simple plain Page.

![image](https://github.com/user-attachments/assets/14fbee5a-5c0f-4cd8-a356-4e72204339dd)

**Comment by inkerton** [comment]
Also I guess you were busy today Do read out the comments under issue #98 

And let me know where I can get the env values.
@anuj123upadhyay

**Comment by anuj123upadhyay** [comment]
okk , i assign this to you
