### ISSUE TITLE
Make Contact us page responsive 

### ISSUE THREAD

**Issue by SurajPrakash24** [anuj123upadhyay/MegaBlog#131]
The existing contact page is not responsive for all device width. I want to make it responsive so that it fits to any device width.

@anuj123upadhyay  Plz assign this issue to me under gssoc-ext level 3 and hacktoberfest.

I have checked it and attached screenshots for mobile device.
![IMG_20241012_161703](https://github.com/user-attachments/assets/b4c5b368-89d9-45d5-ad15-6498b1e3eeb3)
![IMG_20241012_161654](https://github.com/user-attachments/assets/cdbbc939-313d-4151-90eb-3e5ad29d6acc)

**Comment by anuj123upadhyay** [comment]
okk, i assign this to you
