### ISSUE TITLE
[UI Enhancement]: Change the header 

### ISSUE THREAD

**Issue by inkerton** [anuj123upadhyay/MegaBlog#159]
![image](https://github.com/user-attachments/assets/23d0e7d9-d045-474e-aff9-930bcbf94068)

Improving the header to be more responsive
Change the dark-light toggle button

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/eedcbbd6-aac9-4ac5-9cfd-a4bd08340225

**Comment by neerajyadavrewa** [comment]
hi @anuj123upadhyay  i  can make it more attractive and good looking please assign this issue to me
