### ISSUE TITLE
Adding Press Kit page 

### ISSUE THREAD

**Issue by Ayan-Khan79** [anuj123upadhyay/MegaBlog#191]
Problem: The "Press Kit" link on the website currently doesn’t redirect to a dedicated page, causing confusion for users and media professionals.

<img width="941" alt="image" src="https://github.com/user-attachments/assets/f5036c62-17eb-49f4-a523-2c8d2d9bc384">

Solution: Implement a fully functional Press Kit page that the link redirects to, containing key media resources about your project.

@anuj123upadhyay  Please assign this issue under gssoc and hacktoberfest label, so I can start working on it...

**Comment by anuj123upadhyay** [comment]
okk i have assigned this to you

**Comment by Ayan-Khan79** [comment]
@anuj123upadhyay  Task completed! Closing issue now..
