### ISSUE TITLE
Improve Signup Page with Confirm Password, Password Toggle, and Strength Validation

### ISSUE THREAD

**Issue by sharayuanuse** [anuj123upadhyay/MegaBlog#2]
Currently, the signup page lacks certain essential features that ensure a smooth user experience and security:

1. Confirm Password Field: The form does not include a confirm password input, which is crucial to prevent mistyped passwords. Implementing this feature would allow users to verify their passwords before submission.

2. Password Visibility Toggle: For better usability, a "Show Password" toggle should be added to allow users to see the password while typing. This can reduce errors, especially on mobile devices.

3. Password Strength Validation: To enhance security, the password field should validate the following conditions before allowing submission:

- Minimum length of 8 characters.
- Contains at least one special character.
- Includes at least one uppercase letter.
- Includes at least one number.
- A real-time indicator should display whether the password meets these conditions.

**Comment by anuj123upadhyay** [comment]
ok , I will assign this issue to you

**Comment by anuj123upadhyay** [comment]
@SuyashSingh01  it already assigned to @sharayuanuse

**Comment by anuj123upadhyay** [comment]
ok , i will also assigned to you
