### ISSUE TITLE
[Enhance]: Add hero section

### ISSUE THREAD

**Issue by inkerton** [anuj123upadhyay/MegaBlog#20]
I want to add a hero section instead of the todo and login to read posts there should be a small intro about the Project. I wan to add a hero section in the home page. 
![image](https://github.com/user-attachments/assets/e83ff50c-7167-4c8d-be25-4d59f8957b94)

**Comment by inkerton** [comment]
@anuj123upadhyay I want to add something like this 
![image](https://github.com/user-attachments/assets/1b9fbb7d-9222-4310-8fd9-ef3f1186e2ed)


Let me know about the color scheme or any other opinion you may have.

**Comment by anuj123upadhyay** [comment]
It is looking good go ahead

**Comment by inkerton** [comment]
@anuj123upadhyay any color preference ???

**Comment by anuj123upadhyay** [comment]
You can choose any thing but matches with overall color of the app although I donot have great design skill so you can choose from your side
