### ISSUE TITLE
add loading when the user click sign in

### ISSUE THREAD

**Issue by AyushSharma72** [anuj123upadhyay/MegaBlog#24]
when the user click sign in there is no  loading 
i want t o add loading spinner when the user clicks the sig in button 

it will enhance user experience the user will know that the website is processing its request of sign in

![image](https://github.com/user-attachments/assets/fd543eb1-2f6f-43fc-bbfb-5c64c762c9b5)

@anuj123upadhyay  please assign this issue to me

**Comment by anuj123upadhyay** [comment]
Okk

**Comment by ar1701** [comment]
I want to contribute on this, can you please assign it to me ?

**Comment by AyushSharma72** [comment]
> I want to contribute on this, can you please assign it to me ?

Already pr is submitted raise other issue
