### ISSUE TITLE
Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [anuj123upadhyay/MegaBlog#256]
Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**Comment by TBorundia** [comment]
@anuj123upadhyay , please assign this issue to me under GSSoC.
Thank You !!

**Comment by anuj123upadhyay** [comment]
It's already implemented

**Comment by TBorundia** [comment]
@anuj123upadhyay ,
Thanks for the update! I hadn’t seen it on the deployed website, so I apologize for the confusion. If needed, I’d be happy to implement. Thank You !!
