### ISSUE TITLE
Automated project structure updation using github workflows, python scripts and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [anuj123upadhyay/MegaBlog#275]
Currently, we dont have the automated project structure updation in our repository. It'll be benefitial for the new commers to understand the project structure from readme itself and reduces the manual work as well.

### Proposed Solution

Automated project structure updation using github workflows, python scripts and action bot

The project structure automation process enhances repository organization and accessibility for contributors by leveraging GitHub Actions and a Python script.

### Screenshots

![image](https://github.com/user-attachments/assets/26bbda18-4082-4d17-8222-1488fbcdb3fb)

**Comment by anuj123upadhyay** [comment]
Ok I assign this issue to you
