### ISSUE TITLE
[FEATURE] Implementing oAuth like google,twitter and github

### ISSUE THREAD

**Issue by Edasgh** [anuj123upadhyay/MegaBlog#283]
I want to add oauth using google, twitter & github in the login & signup page
I would like to work on this issue.
Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels
![Screenshot 2024-10-25 120135](https://github.com/user-attachments/assets/f40de103-a333-4cfe-a400-a7439209b70d)

**Comment by anuj123upadhyay** [comment]
Okk , I have assigned the issue to you
