### ISSUE TITLE
Add Feature for changing the profile picture: setup backend and frontend in order to implement the feature end to end

### ISSUE THREAD

**Issue by ShivanshPlays** [anuj123upadhyay/MegaBlog#315]
![Screenshot 2024-10-28 055122](https://github.com/user-attachments/assets/f1592655-4e01-45d9-8923-0c517f0dd7d5)

**Comment by ShivanshPlays** [comment]
@anuj123upadhyay please assign

**Comment by anuj123upadhyay** [comment]
okk @ShivanshPlays  i have assigned you level3
