### ISSUE TITLE
Incomplete Implementation of User Profile  details Update

### ISSUE THREAD

**Issue by ShivanshPlays** [anuj123upadhyay/MegaBlog#327]
# Bug Report: Incomplete Implementation of User Profile Update

## Overview

While implementing the **Set User Profile Picture** functionality (#326 ), I discovered that the **Update User Profile Details** feature is not fully implemented. This issue is causing inconsistencies when attempting to modify user profile information, including uploading a profile picture. 

Although I implemented the profile picture, but this is still an issue.....

The incomplete logic affects user experience by limiting profile updates. A screen recording of the issue has been provided for clarity. Below, I describe the issue, current behavior, and steps to resolve it.

---

## Bug Description

When attempting to **edit user profile details** (e.g., name, bio, and profile picture), the current code logic fails to update all user information properly. Specifically:
- The **updateUser** method is not connected to backend API call

The incomplete implementation blocks users from making permanent necessary changes to their profiles.

---

## Steps to Reproduce

1. Go to the **User Profile Edit** page.
2. Attempt to update any profile field (e.g., **name or bio**).
3. Click **Save** to submit the changes.
4. Observe that:
   - Profile data is partially updated.
   
Refer to the **screen recording** below for a complete demonstration of the bug:
[Screen Recording Link Here]

https://github.com/user-attachments/assets/a51ce624-71d0-4cb0-8e8c-0cf1859a0d2f

## Expected Behavior

- Users should be able to **update all profile fields**, including their profile picture, name, and other details.
- Upon clicking **Save**, the updated information should be reflected in backend
- Errors, if any, should be handled gracefully with

**Comment by anuj123upadhyay** [comment]
Okk i assign this issue to you
