### ISSUE TITLE
Carousel Lacks Auto-Scroll Feature for Blog Posts

### ISSUE THREAD

**Issue by IkkiOcean** [anuj123upadhyay/MegaBlog#340]
**Description:**
The blog post carousel currently displays posts without auto-scrolling, requiring users to manually navigate between slides. This can lead to a less engaging experience, as users may miss out on viewing additional blog posts if they don't manually interact with the carousel.

** Current State **
<img width="1280" alt="Screenshot 2024-10-29 at 5 11 54 PM" src="https://github.com/user-attachments/assets/f245b4b1-4c70-407a-90b9-69a4fb021d9c">

**Expected Behavior:**
The carousel should automatically scroll through blog posts at a set interval, allowing users to view posts without manual input. Users should also be able to pause auto-scrolling on hover for better control.

**Proposed Solution:**
1. Implement an auto-scroll feature that scrolls the carousel items every few seconds.
2. Add a hover event that pauses the auto-scroll while the user interacts with the carousel and makes the card pop outwards.

**Technical Details:**
- Set an auto-scroll interval (e.g., 3–5 seconds).

**Additional Context:**
Adding this feature will enhance user experience and ensure blog content is passively visible to the audience.

**Comment by anuj123upadhyay** [comment]
Okk i assign this task to you but complete the task as soon as possible as gssoc come very close to its end

**Comment by IkkiOcean** [comment]
> Okk i assign this task to you but complete the task as soon as possible as gssoc come very close to its end

sure sir
