### ISSUE TITLE
Website Theme Not Changing on Mode Switch

### ISSUE THREAD

**Issue by AnushkaChouhan25** [anuj123upadhyay/MegaBlog#373]
The website theme is not updating correctly when switching between light and dark modes. On toggling the mode, website fail to apply the new theme, causing inconsistent styling across the site.

Expected Behavior:

- The entire website should consistently switch between light and dark themes when the mode toggle button is activated.
- All elements, including background colors, text, and icons, should update to match the selected mode for a cohesive appearance.
- 
![image](https://github.com/user-attachments/assets/01616a67-c4fe-4592-b636-91bdb746c7f0)

**Comment by anuj123upadhyay** [comment]
okk i assigned this issue to you
