### ISSUE TITLE
Affiliate Program's Page 

### ISSUE THREAD

**Issue by inkerton** [anuj123upadhyay/MegaBlog#55]
There is no Affiliate Program's Page. It should provide a general info on how to get started with it and how the affiliate programs generally works.

**Comment by inkerton** [comment]
@anuj123upadhyay  Kindly add gssoc-extnd, hacktoberfest-accepted and level2 or level3 tag to the issue I have already started working on it .

**Comment by inkerton** [comment]
@anuj123upadhyay What are you expecting in the prss kit page ? Give me some info and I will work accordingly.

**Comment by anuj123upadhyay** [comment]
@inkerton  can you please work on the individual post and also make it attractive 
![ScreenshotMegablog](https://github.com/user-attachments/assets/e9b3170c-37c0-400b-bd34-91758bfccdc2)
like make it in proper  alignment with the proper size of thumbnail with proper spacing among the lines  and the sharing buttons should also be place in proper manner, if you are willing to work on this then make another pr , becoz i like your work
if yes then good 
if no then i will make an issue and assign this to others

**Comment by inkerton** [comment]
- [x] I will make a separate issue for this and work on it @anuj123upadhyay 
I will complete this in 3 days this one will take more time I will need to study and then change the current code so that's why.
