### ISSUE TITLE
[Feature]:Implement the feature of Sharing the blog posts on a linkedin, twitter, whatsapp

### ISSUE THREAD

**Issue by anuj123upadhyay** [anuj123upadhyay/MegaBlog#6]
Implement the feature of sharing the post may be you are a writer of that post or just a reader of that post

**Comment by Prajyot05** [comment]
Hey, could you assign this task to me? @anuj123upadhyay

**Comment by anuj123upadhyay** [comment]
okk , I will assign this task to you

**Comment by Prajyot05** [comment]
I am unable to use the app to its full extent as I cannot login, is there a way for you to remove that constraint for some time? @anuj123upadhyay

**Comment by Prajyot05** [comment]
I have solved the issue and raised a pull request. Pls mark the appropriate level tag to this issue as well. Thank you.
