### ISSUE TITLE
Scroll to top button with animation

### ISSUE THREAD

**Issue by Sawan-Kushwah** [anuj123upadhyay/MegaBlog#67]
As we have a blog website so there is need of this button as someone reaches to end after reading blog he has to scroll to top manually which create bad user experience so we can 

add this button 
something like this 

https://github.com/user-attachments/assets/99cbff0d-bf74-411c-8a56-f67f34d7d234

**Comment by anuj123upadhyay** [comment]
Okk I have assigned this to you

**Comment by Sawan-Kushwah** [comment]
@anuj123upadhyay kind request Can you please level up for this task as it required to build different component after seeing my work
