### ISSUE TITLE
Customer support page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [anuj123upadhyay/MegaBlog#81]
i can build it 
assign me

**Comment by anuj123upadhyay** [comment]
work on it as i assigned this to you

**Comment by anuj123upadhyay** [comment]
hey @Sawan-Kushwah it causes a problem after merge this #75  pr now none of the functionality work  from the footer or from the navbar,  as there is still a contact us button on the navabar which is not working try to remove this and make another pr

**Comment by anuj123upadhyay** [comment]
> hey @Sawan-Kushwah it causes a problem after merge this #75 pr now none of the functionality work from the footer or from the navbar, as there is still a contact us button on the navabar which is not working try to remove this and make another pr

first resolve this issue  then work on other issues

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/fe4c42c8-5fec-4f7c-bcc1-d70fa12667ce

@anuj123upadhyay 
see everything working fine here which issue are you talking about 
every link from navbar and footer is working

**Comment by Sawan-Kushwah** [comment]
@anuj123upadhyay can you please explain me in a video formate so i can have a better idea what the exact issue

**Comment by anuj123upadhyay** [comment]
ok raise a pull request for this
