### ISSUE TITLE
[BUG] : Page Heading not visible in Dark mode | gssoc-extd

### ISSUE THREAD

**Issue by Hamza1821** [anuj123upadhyay/MegaBlog#86]
### **Page Heading not visible in Dark mode | gssoc-extd**

in Light Mode
![Screenshot 2024-10-09 at 07-01-52 MegaBlog](https://github.com/user-attachments/assets/3cb1afe8-3206-4107-8474-8ebccd00cd34)

in Dark Mode

![Screenshot 2024-10-09 at 07-01-34 MegaBlog](https://github.com/user-attachments/assets/6ad1686d-89ff-4088-a753-f3ebb82fb3a3)

### **please assign this to me under gssoc-extd level 2**

**Comment by anuj123upadhyay** [comment]
ok , i am assigning this task to you but you also have to change this issue in the Blogpost title of each individual in dark mode 
![Uploading DarkmodeMegabloProblem.png…]()

**Comment by anuj123upadhyay** [comment]
here below the thumbnail nothing is properly visibly and also after clicking it in the blog the text is not in proper color to withstand with the dark mode so also resolve this issue

**Comment by Hamza1821** [comment]
please assign #85 to me under gssoc-extd level 3
